version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: jarvis
       MYSQL_DATABASE: panda
       MYSQL_USER: panda
       MYSQL_PASSWORD: panda

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: panda
       WORDPRESS_DB_PASSWORD: panda
       WORDPRESS_DB_NAME: panda
volumes:
    db_data: {}